#!/bin/bash
BITCOIN_CORE_BIN_DIR="${PROJECT_ROOT}/bitcoin-0.15.1/bin"
LITECOIN_CORE_BIN_DIR="${PROJECT_ROOT}/litecoin-0.15.0/bin"

RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m' # Light blue
NC='\033[0m' # No Color
