#!/bin/bash
# Set up binaries for either Bitcoin or Litecoin.
# The location of the directory that contains the relevant binaries can be set in
# `/lib/config`. If you do not set a location here, a Zenity GUI will run that
# prompts the user to select the directory that contains the relevant binaries.

set -o nounset
set -o errexit

function select_coin {
  TITLE="Select a Core Client to Use"
  PROMPT="Pick an option:"
  OPTIONS=("Bitcoin" "Litecoin")
  echo "$TITLE"
  PS3="$PROMPT "
  select OPT in "${OPTIONS[@]}" "Quit"; do
    case "$REPLY" in
      1) break;;
      2) break;;
      $((${#OPTIONS[@]}+1))) echo "End"; break;;
      *) echo "Invalid option. Try again.";
      continue;;
    esac
  done
  echo "You selected $OPT."
  COIN="${OPT,,}"
}

# If a value for the directory path to the binary files has not been set, use
# Zenity to allow the user to select it.
function set_binary_dir {
  if [[ ${OPT} == "Bitcoin" ]]; then
    CORE_DIR=${BITCOIN_CORE_BIN_DIR}
  elif [[ ${OPT} == "Litecoin" ]]; then
    CORE_DIR=${LITECOIN_CORE_BIN_DIR}
  fi
  if [[ ${CORE_DIR} == "false" ]]; then
    CORE_DIR=$(zenity --file-selection --title="Select the directory that contains ${OPT} binaries." --filename=${PWD}/ --directory)
    case $? in
      0)
      echo "\"${CORE_DIR}\" selected.";;
      1)
      echo "No directory selected.";;
      -1)
      echo "An unexpected error has occurred.";;
    esac
  fi
  # Confirm and repeat if necessary
  echo "The directory containing ${OPT} binaries is set to ${CORE_DIR}"
  read -p "Is this correct [Yn]? Enter N if you'd like to select a different location:" CONT
  case "${CONT}" in
    y|Y );;
    n|N ) set_binary_dir ${OPT};;
    * ) echo "Invalid selection";;
  esac
}

# Set up commands for daemon, command line client and GUI.
function set_commands {
  echo "-------------------------------------------------"
  echo "WARNING. OVERWRITING SYMLINKS TO ${OPT} BINARIES."
  echo "-------------------------------------------------"
  read -p "Do you wish to proceed? [y/N]" PROCEED
  case $PROCEED in
    [Yy]* )
    cd /usr/local/bin &&
    sudo rm -f ${COIN}-cli ${COIN}d ${COIN}-qt
    sudo ln -s ${CORE_DIR}/${COIN}-cli ${COIN}-cli
    sudo ln -s ${CORE_DIR}/${COIN}d ${COIN}d
    sudo ln -s ${CORE_DIR}/${COIN}-qt ${COIN}-qt
    echo "Symlinks added. To run binaries:"
    echo "${COIN}-cli"
    echo "${COIN}d"
    echo "${COIN}-qt"
    ;;
    [Nn]* )
    echo "No symlinks added. To run binaries:"
    echo "${CORE_DIR}/${COIN}-cli"
    echo "${CORE_DIR}/${COIN}d"
    echo "${CORE_DIR}/${COIN}-qt"
    ;;
    * ) echo "Please answer yes or no."
    ;;
  esac
}

function setup_binaries {
  select_coin
  set_binary_dir
  set_commands
}
